<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>learning_wpf_opencv</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.13.0.20260627" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\resources\EDSR_Tensorflow\models\EDSR_x4.pb">
      <Link>resources\EDSR_Tensorflow\models\EDSR_x4.pb</Link>

      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>










</Project>
